dm/urls.py
# coding: utf-8




from django.conf.urls import url
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/", permanent=True), name="dm_index"),
    url(r'^claim$', views.Claim.as_view(), name="dm_claim"),
    url(r'^claim/confirm/(?P<token>[^/]+)$', views.ClaimConfirm.as_view(), name="dm_claim_confirm"),
]

fprs/urls.py
from __future__ import annotations
from django.urls import path, re_path
from . import views

app_name = "fprs"

urlpatterns = [
    # Manage fingerprints
    path('person/<key>/', views.PersonFingerprints.as_view(), name="person_list"),
    # Activate fingerprints
    re_path(r'^person/(?P<key>[^/]+)/(?P<fpr>[0-9A-F]+)/activate/$', views.SetActiveFingerprint.as_view(),
            name="person_activate"),
]

nm2/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from backend.mixins import VisitorTemplateView
from django.conf import settings
from rest_framework import routers
from django.contrib import admin
import django.conf.urls
import backend.views as bviews
import process.views as pviews
import public.views as public_views
import nmlayout.views as nmviews

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'persons', bviews.PersonViewSet, "persons")
router.register(r'processes', pviews.ProcessViewSet, "processes")

django.conf.urls.handler403 = nmviews.Error403.as_view()
django.conf.urls.handler404 = nmviews.Error404.as_view()
django.conf.urls.handler500 = nmviews.Error500.as_view()


urlpatterns = [
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    path('i18n/', include('django.conf.urls.i18n')),
    path(r'', VisitorTemplateView.as_view(template_name='index.html'), name="home"),
    path('license/', VisitorTemplateView.as_view(template_name='license.html'), name="root_license"),
    path('faq/', VisitorTemplateView.as_view(template_name='faq.html'), name="root_faq"),
    path('login/', nmviews.Login.as_view(), name='login'),
    path('members/', public_views.Members.as_view(), name="members"),
    path('legacy/', include("legacy.urls")),
    path('person/', include("person.urls")),
    path('public/', include("public.urls")),
    path('am/', include("restricted.urls")),
    path('fprs/', include("fprs.urls")),
    path('process/', include("process.urls")),
    path('dm/', include("dm.urls")),
    path('api/', include("api.urls")),
    path('apikeys/', include("apikeys.urls")),
    path('keyring/', include("keyring.urls")),
    path('wizard/', include("wizard.urls")),
    path('mia/', include("mia.urls")),
    path('minechangelogs/', include("minechangelogs.urls")),
    path('sitechecks/', include("sitechecks.urls")),
    path('deploy/', include("deploy.urls")),
    path('rest/api/', include(router.urls)),
    path('signon/', include("signon.urls")),
    path('impersonate/', include("impersonate.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

person/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = "person"

urlpatterns = [
    path('', RedirectView.as_view(url="/", permanent=True), name="index"),
    path('<key>/', views.Person.as_view(), name="show"),
    path('<key>/edit_ldap/', views.EditLDAP.as_view(), name="edit_ldap"),
    path('<key>/edit_bio/', views.EditBio.as_view(), name="edit_bio"),
    path('<key>/edit_email/', views.EditEmail.as_view(), name="edit_email"),
    # AM preferences editor
    path('<key>/amprofile/', views.AMProfile.as_view(), name="amprofile"),
    path('identities/', views.Identities.as_view(), name='identities_self'),
    path('identities/<key>/', views.Identities.as_view(), name='identities'),
]

process/urls.py
from __future__ import annotations
from django.urls import path
from . import views

urlpatterns = [
    path('', views.List.as_view(), name="process_list"),
    # AM Personal page
    path('am-dashboard/', views.AMDashboard.as_view(), name="process_am_dashboard"),
    path('create/<key>/', views.Create.as_view(), name="process_create"),
    path('<int:pk>/', views.Show.as_view(), name="process_show"),
    path('<int:pk>/intent/', views.ReqIntent.as_view(), name="process_req_intent"),
    path('<int:pk>/sc_dmup/', views.ReqAgreements.as_view(), name="process_req_sc_dmup"),
    path('<int:pk>/advocate/', views.ReqAdvocate.as_view(), name="process_req_advocate"),
    path('<int:pk>/am_ok/', views.ReqAM.as_view(), name="process_req_am_ok"),
    path('<int:pk>/keycheck/', views.ReqKeycheck.as_view(), name="process_req_keycheck"), # TODO: test
    path('<int:pk>/approval/', views.ReqApproval.as_view(), name="process_req_approval"), # TODO: test
    path('<int:pk>/add_log/', views.AddProcessLog.as_view(), name="process_add_log"),
    path('<int:pk>/<type>/statement/create/', views.StatementCreate.as_view(), name="process_statement_create"),
    path('<int:pk>/<type>/statement/<int:st>/delete/', views.StatementDelete.as_view(), name="process_statement_delete"),
    path('<int:pk>/<type>/statement/<int:st>/raw/', views.StatementRaw.as_view(), name="process_statement_raw"),
    path('<int:pk>/assign_am/', views.AssignAM.as_view(), name="process_assign_am"),
    path('<int:pk>/unassign_am/', views.UnassignAM.as_view(), name="process_unassign_am"),
    path('<int:pk>/mailbox/download/', views.MailArchive.as_view(), name="process_mailbox_download"), # TODO: test
    path('<int:pk>/mailbox/', views.DisplayMailArchive.as_view(), name="process_mailbox_show"), # TODO: test
    path('<int:pk>/update_keycheck/', views.UpdateKeycheck.as_view(), name="process_update_keycheck"), # TODO: test
    path('<int:pk>/download_statements/', views.DownloadStatements.as_view(), name="process_download_statements"), # TODO: test
    path('<int:pk>/rt_ticket/', views.MakeRTTicket.as_view(), name="process_rt_ticket"),
    path('<int:pk>/approve/', views.Approve.as_view(), name="process_approve"),
    path('emeritus/', views.Emeritus.as_view(), name="process_emeritus_self"),
    path('emeritus/<key>/', views.Emeritus.as_view(), name="process_emeritus"),
    path('<int:pk>/cancel/', views.Cancel.as_view(), name="process_cancel"),
]

process/forms.py
from django import forms


class StatementForm(forms.Form):
    statement = forms.CharField(
        label="Signed statement", widget=forms.Textarea(attrs={"rows": 25, "cols": 80, "class": "text-monospace"}))

    def __init__(self, *args, **kw):
        self.fpr = kw.pop("fpr")
        super(StatementForm, self).__init__(*args, **kw)

    def clean_statement(self):
        from keyring.models import Key
        text = self.cleaned_data["statement"]

        try:
            key = Key.objects.get_or_download(self.fpr)
        except RuntimeError as e:
            raise forms.ValidationError("Cannot download the key: " + str(e))

        try:
            plaintext = key.verify(text)
        except RuntimeError as e:
            raise forms.ValidationError(
                "Cannot verify the signature: " + str(e))

        return (text, plaintext)

process/views.py
from __future__ import annotations
from django.utils.translation import ugettext as _
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView
from django.utils.timezone import now
from django.db import transaction
from django import forms, http
from django.core.exceptions import PermissionDenied
from django.contrib import messages as django_messages
from django.urls import reverse
from rest_framework import viewsets
from backend.shortcuts import build_absolute_uri
from backend.mixins import VisitorMixin, VisitPersonMixin, TokenAuthMixin
from backend import const
import backend.models as bmodels
from nm2.lib import assets
import nm2.lib.forms
from .mixins import VisitProcessMixin, RequirementMixin, StatementMixin
import datetime
import requests
from six.moves import shlex_quote
from . import models as pmodels
from .forms import StatementForm
from .serializers import ProcessSerializer
from . import ops as pops


# Catcher for HTTPError
def _catch_http_error(request, e, ret_dest):
    django_messages.add_message(
        request,
        django_messages.ERROR,
        _("The server met an error: {}").format(e),
    )
    return redirect(ret_dest)


class ProcessViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Export process information
    """
    queryset = pmodels.Process.objects.filter(
        closed_time__isnull=True).order_by("started")
    serializer_class = ProcessSerializer


class List(VisitorMixin, TemplateView):
    """
    List active and recently closed processes
    """
    assets = [assets.DataTablesBootstrap4]
    template_name = "process/list.html"

    def get_context_data(self, **kw):
        ctx = super(List, self).get_context_data(**kw)
        ctx["current"] = pmodels.Process.objects.filter(
            closed_time__isnull=True).order_by("applying_for").select_related("person")
        cutoff = now() - datetime.timedelta(days=30)
        ctx["last"] = pmodels.Process.objects.filter(
            closed_time__gte=cutoff).order_by("-closed_time").select_related("person")
        return ctx


class AMDashboard(VisitorMixin, TemplateView):
    require_visitor = "am"
    template_name = "process/amdashboard.html"

    def _show_process(self, process):
        """
        Return True if the process should be shown in the dashboard, False if
        it should not.
        """
        if process.frozen_by_id is not None or process.approved_by_id is not None:
            return True

        if process.hide_until and process.hide_until > now():
            return False

        if process.applying_for in (const.STATUS_EMERITUS_DD, const.STATUS_REMOVED_DD):
            return True

        for_ga = process.applying_for in (
            const.STATUS_DC_GA, const.STATUS_DM_GA)

        needs_am_report = False
        for req in process.requirements.all():
            if req.type == "intent":
                if not req.approved_by_id:
                    return False
                # Hide all processes with a statement of intent approved less
                # than 4 days ago
                if not for_ga and req.approved_time + datetime.timedelta(days=4) > now():
                    return False
            for req_type in ("sc_dmup", "advocate", "keycheck"):
                if req.type == req_type and not req.approved_by_id:
                    return True
            if req.type == "am_ok":
                needs_am_report = req.approved_by_id is None

        if needs_am_report and process.current_am_assignment:
            return False

        return True

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)

        import process.models as pmodels
        from sitechecks.models import Inconsistency
        processes = []
        approved_processes = []
        fd_approved_processes = []
        for p in pmodels.Process.objects.filter(closed_time__isnull=True).order_by("applying_for"):
            # Shows in fd_approved_processes even hidden processes, so DAM can't miss these
            if p.applying_for in ['dd_nu', 'dd_u']:
                if p.approved and p.approved_by.am_or_none and not p.approved_by.am.is_dam:
                    fd_approved_processes.append(p)
            if not self._show_process(p):
                continue
            if p.approved:
                approved_processes.append(p)
            else:
                processes.append(p)
        ctx["current_processes"] = processes
        ctx["approved_processes"] = approved_processes
        ctx["fd_approved_processes"] = fd_approved_processes

        ctx["am_available"] = bmodels.AM.list_available(free_only=True)

        today = now().date()
        ctx["inconsistencies"] = [
            i for i in Inconsistency.objects.filter(last_seen__gte=today)
                                            .order_by("-last_seen", "person", "process", "tag", "text")
            if (i.ignore_until is None or i.ignore_until < today)
        ]

        for a in pmodels.AMAssignment.objects.filter(
                            am=self.request.user.am, process__closed_time__isnull=True, unassigned_by__isnull=True) \
                        .select_related("process") \
                        .order_by("process__started"):
            if a.paused:
                ctx.setdefault("am_prog_hold", []).append(a.process)
            else:
                ctx.setdefault("am_prog_am", []).append(a.process)

        return ctx


class Create(VisitPersonMixin, FormView):
    """
    Create a new process
    """
    require_visit_perms = "request_new_status"
    template_name = "process/create.html"

    def get_context_data(self, **kw):
        ctx = super(Create, self).get_context_data(**kw)
        current = []
        current.extend(pmodels.Process.objects.filter(
            person=self.person, closed_time__isnull=True))
        ctx["current"] = current
        ctx["wikihelp"] = "https://wiki.debian.org/DebianDeveloper/JoinTheProject/NewMember/StatusChangeStep"
        return ctx

    def get_form_class(self):
        whitelist = self.person.possible_new_statuses
        choices = [(x.tag, x.ldesc)
                   for x in const.ALL_STATUS if x.tag in whitelist]
        if not choices:
            raise PermissionDenied

        class Form(nm2.lib.forms.BootstrapAttrsMixin, forms.Form):
            applying_for = forms.ChoiceField(
                label=_("Apply for status"), choices=choices, required=True)
        return Form

    def form_valid(self, form):
        applying_for = form.cleaned_data["applying_for"]
        if applying_for == const.STATUS_EMERITUS_DD:
            return redirect(reverse("process_emeritus", args=[self.person.lookup_key]))

        op = pops.ProcessCreate(
            person=self.person, applying_for=applying_for, audit_author=self.request.user)
        op.execute(self.request)

        return redirect(op.new_process.get_absolute_url())


class Show(VisitProcessMixin, TemplateView):
    """
    Show a process
    """
    template_name = "process/show.html"

    def get_context_data(self, **kw):
        ctx = super(Show, self).get_context_data(**kw)
        ctx["status"] = self.compute_process_status()
        ctx["picture"] = self.person.get_picture_url()
        return ctx


class AddProcessLog(VisitProcessMixin, View):
    """
    Add an entry to the process or requirement log
    """
    @transaction.atomic
    def post(self, request, *args, **kw):
        logtext = request.POST.get("logtext", "").strip()
        action = request.POST.get("add_action", "undefined")
        req_type = request.POST.get("req_type", None)

        if req_type:
            requirement = get_object_or_404(
                pmodels.Requirement, process=self.process, type=req_type)
            target = requirement
        else:
            requirement = None
            target = self.process

        visit_perms = target.permissions_of(self.request.user)

        op = None
        if action in ("log_private", "log_public"):
            if "add_log" not in visit_perms:
                raise PermissionDenied
            if logtext:
                op_args = {}
                if req_type:
                    op_args["requirement"] = requirement
                else:
                    op_args["process"] = self.process
                op = pops.ProcessAddLogEntry(
                    audit_author=self.request.user,
                    audit_notes=logtext,
                    is_public=action == "log_public",
                    **op_args)
        elif action == "log_public":
            if "add_log" not in visit_perms:
                raise PermissionDenied
            action = ""
        elif action == "req_unapprove":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.RequirementUnapprove(
                audit_author=self.request.user, audit_notes=logtext or "Requirement unapproved",
                requirement=requirement)
        elif action == "req_approve":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.RequirementApprove(
                audit_author=self.request.user, audit_notes=logtext or "Requirement approved", requirement=requirement)
        elif action == "proc_pause":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.ProcessPause(
                audit_author=self.request.user, audit_notes=logtext or "Process paused", process=self.process)
        elif action == "proc_unpause":
            if action not in visit_perms:
                raise PermissionDenied
            op = pops.ProcessUnpause(
                audit_author=self.request.user, audit_notes=logtext or "Process resumed", process=self.process)
        elif action == "proc_freeze":
            if action not in visit_perms:
                raise PermissionDenied

process/templates/process/show.html
{% extends "process/nm2-base.html" %}
{% load nm %}
{% load i18n %}

{% block content %}

<h1 class="d-flex">
  {% if picture %}
  <img class="mr-2 personpic" src="{{picture}}"></img>
  {% endif %}
  {{person.fullname}}
</h1>

<table class="table table-sm">
  <tr>
    <th>{% trans "Applying for" %}</th>
    <td><b>{{process.applying_for|desc_status}}</b></td>
  </tr>
  <tr>
    <th>{% trans "Applicant" %}</th>
    <td>
      <a href="{{person.get_absolute_url}}">{{person.fullname}} &lt;{{person.preferred_email}}&gt;</a>,
      {% blocktrans with status=person|desc_status %}currently <i>{{status}}</i>{% endblocktrans %}
    </td>
  </tr>
  <tr><th>{% trans "OpenPGP fingerprint" %}</th><td>{{person.fpr|fingerprint}}{% if "edit_fpr" in visit_perms %} <a id="edit_fpr_link" class="btn btn-sm btn-primary ml-2" href="{% url 'fprs:person_list' key=person.lookup_key %}"><span class="fa fa-edit"></span> {% trans "Edit" %}</a>{% endif %}</td></tr>
  <tr><th>{% trans "Activity timespan" %}</th><td>{{status.log_first.logdate|date:"Y-m-d"}} to {{status.log_last.logdate|date:"Y-m-d"}}</td></tr>
  <tr>
    <th>{% trans "Status" %}</th>
    <td>
      {% if process.closed %}
        {% trans "Closed." %}
        {% if process.rt_ticket is not None %}{% trans "RT ticket:" %} <a href="https://rt.debian.org/{{process.rt_ticket}}">{{process.rt_ticket}}</a>.{% endif %}
      {% else %}
        {% if process.frozen_by %}
          {% if process.approved_by %}
            {% blocktrans with process_approved_by_a_link=process.approved_by.a_link process_approved_time=process.approved_time|date:"Y-m-d" %}Approved
by {{process_approved_by_a_link}} on {{process_approved_time}}.{% endblocktrans %}
            {% if process.rt_ticket is not None %}{% trans "RT ticket:" %} <a href="https://rt.debian.org/{{process.rt_ticket}}">{{process.rt_ticket}}</a>.{% endif %}
          {% else %}
            {% blocktrans with process_frozen_by_a_link=process.frozen_by.a_link process_frozen_time=process.frozen_time|date:"Y-m-d" %}Frozen
for review by {{process_frozen_by_a_link}} on {{process_frozen_time}}.{% endblocktrans %}
          {% endif %}
        {% else %}
          {% if process.approved_by %}
            {% blocktrans with process_approved_by_a_link=process.approved_by.a_link process_frozen_time=process.frozen_time|date:"Y-m-d" %}Inconsistent
state: approved by {{process_approved_by_a_link}} on {{process_frozen_time}},
but not frozen for review.{% endblocktrans %}
          {% elif not status.requirements_missing %}
            {% trans "Waiting for review." %}
          {% else %}
            {% trans "Collecting requirements." %}
          {% endif %}
        {% endif %}
      {% endif %}
    </td>
  </tr>

  {% if process.closed %}
  <tr>
    <th>{% trans "Completed" %}</th>
    <td>{{process.closed_time|date:"Y-m-d"}}</td>
  </tr>
  {% endif %}

  {% if "advocate" in status.requirements %}
  <tr>
    <th>Advocate{{status.advocates|pluralize}}</th>
    <td>
      {% for a in status.advocates %}
      {{a.a_link}}{% if not forloop.last %}, {% endif %}
      {% empty %}
      <a href="{{status.requirements.advocate.get_absolute_url}}">{% trans "none yet" %}</a>
      {% endfor %}
    </td>
  </tr>
  {% endif %}

  {% with process.current_am_assignment as am %}
  {% if am %}
  <tr>
    <th>{% trans "Application Manager" %}</th>
    <td>
      {{am.am.person.a_link}} {% trans "assigned by" %} {{am.assigned_by.a_link}} {% trans "on" %} {{am.assigned_time|date:"Y-m-d"}}
      {% if "am_unassign" in visit_perms %}
      <form style="display: inline" class="form-inline" id="am_unassign" action="{% url 'process_unassign_am' pk=process.pk %}" method="POST">{% csrf_token %}
        <button class="btn btn-warning btn-sm ml-2" type="submit"><span class="fa fa-remove"></span> {% trans "Unassign" %}</button>
      </form>
      {% endif %}
    </td>
  </tr>
  {% endif %}
  {% endwith %}

  <tr>
    <th>{% trans "Debian account name" %}</th>
    <td>
      {% if "edit_ldap" in visit_perms %}
        <a href="{% url 'person:edit_ldap' key=person.lookup_key %}">
          {% if person.ldap_fields.uid %}
          {{person.ldap_fields.uid}}
          {% else %}
          <i>✘ {% trans "missing" %}</i>
          {% endif %}
        </a>
      {% else %}
          {% if person.ldap_fields.uid %}
          {{person.ldap_fields.uid}}
          {% else %}
          <i>✘ {% trans "missing" %}</i>
          {% endif %}
      {% endif %}
    </td>
  </tr>

  {% if "edit_ldap" in visit_perms %}
  <tr>
    <th>{% trans "LDAP information" %}</th>
    <td>
      <tt>cn={{person.ldap_fields.cn}}, mn={{person.ldap_fields.mn}}, sn={{person.ldap_fields.sn}}, email={{person.ldap_fields.email}}, uid={{person.ldap_fields.uid}}</tt>
      <a class="btn btn-sm btn-primary ml-2" href="{% url 'person:edit_ldap' key=person.lookup_key %}"><span class="fa fa-edit"></span> {% trans "Edit" %}</a>
    </td>
  </tr>
  {% endif %}

  <tr>
    <th>{% trans "Missing requirements" %}</th>
    <td>
      {% if status.requirements_missing %}
        {% for req in status.requirements_missing %}
          {% if "req_view" in req|perms:user %}
            <a class="btn btn-sm btn-outline-danger" id="req_{{req.type}}_missing" href="{{req.get_absolute_url}}">{{req.type_desc}}</a>
          {% else %}
            <span class="btn btn-sm btn-outline-danger disabled" title="{% trans 'Contents are private' %}">{{req.type_desc}}</span>
          {% endif %}
        {% endfor %}
      {% else %}
        {% trans "none" %}
      {% endif %}
    </td>
  </tr>

  <tr>
    <th>{% trans "Requirements ok" %}</th>
    <td>
      {% if status.requirements_ok %}
        {% for req in status.requirements_ok %}
          {% if "req_view" in req|perms:user %}
            <a class="btn btn-sm btn-outline-success" id="req_{{req.type}}_ok" href="{{req.get_absolute_url}}">{{req.type_desc}}</a>
          {% else %}
            <span class="btn btn-sm btn-outline-success disabled" title="{% trans 'Contents are private' %}">{{req.type_desc}}</span>
          {% endif %}
        {% endfor %}
      {% else %}
        {% trans "none" %}
      {% endif %}
    </td>
  </tr>

  {% if "fd_comments" in visit_perms %}
  {% if person.fd_comment %}<tr id="view_person_fd_comment"><th>{% trans "FD comments" %}</th><td>{{person.fd_comment}}</td></tr>{% endif %}
  {% if process.fd_comment %}<tr id="view_process_fd_comment"><th>{% trans "FD comments" %}</th><td>{{process.fd_comment}}</td></tr>{% endif %}
  {% endif %}

  {% if "view_mbox" in visit_perms %}
  <tr id="view_mbox">
    <th>{% trans "Mail archive" %}</th>
    <td>
        <tt><a href="mailto:{{process.archive_email}}">{{process.archive_email}}</a></tt>
        {% with process.current_am_assignment as am %}
        {% if am %}
        <a class="btn btn-sm btn-primary ml-2" href="mailto:{{process.archive_email}},{{person.email}},{{am.am.person.email}}"><span class="fa fa-envelope"></span> {% trans "Email applicant and AM" %}</a>
        {% else %}
        <a class="btn btn-sm btn-primary ml-2" href="mailto:{{process.archive_email}},{{person.email}}"><span class="fa fa-envelope"></span> {% trans "Email applicant" %}</a>
        {% endif %}
        {% endwith %}
        {% if process.mailbox_file %}
        <a class="btn btn-sm btn-primary" href="{% url 'process_mailbox_download' pk=process.pk %}"><span class="fa fa-download"></span> {% trans "(download mail archive)" %}</a>
        <a class="btn btn-sm btn-primary" href="{% url 'process_mailbox_show' pk=process.pk %}"><span class="fa fa-envelope-open"></span> {% trans "display mail archive" %}</a>
        {% else %}
        {% trans "(no mail archive yet)" %}
        {% endif %}
    </td>
  </tr>

  {% comment %} TODO: Requires porting stats backend to new Process
  NOTE: blocktrans needs to be adjusted to use syntax {% blocktrans with name=something%} {{name}}...
  {% if mbox_stats %}
  <tr><th>{% trans "Mailbox stats" %}</th>
      <td>{% blocktrans %}{{mbox_stats.date_first_py|date:"Y-m-d"}} to {{mbox_stats.date_last_py|date:"Y-m-d"}},
{{mbox_stats.num_mails}} mails,{% endblocktrans %}
          <br>
          {% if mbox_stats.median_py %}
            {% if mbox_stats.median_py.days %}{% blocktrans %}{{mbox_stats.median_py.days}}d {% endif %}{{mbox_stats.median_hours}}h median response time{% endblocktrans %}
          {% endif %}
          <span class="mbox_sparkline" values="{{mbox_stats.response_time|join:","}}"></span>
      </td>
  </tr>
  {% endif %}
  {% endcomment %}

  {% endif %}
</table>

<h2 class="mt-3">{% trans "Requirements" %}</h2>

<table class="table table-sm">
  <thead>
    <tr>
      <th>{% trans "Requirement" %}</th>
      <th>{% trans "Approved by" %}</th>
      <th>{% trans "Approved date" %}</th>
      <th>{% trans "Notes" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for req in status.requirements_sorted %}
    <tr>
      {% with req.compute_status as rstatus %}
      <td><a href="{{req.get_absolute_url}}">{{req}}</a></td>
      <td>
        {% if req.approved_by %}
          {{req.approved_by.a_link}}
        {% else %}
          -
        {% endif %}
      </td>
      <td>
        {% if req.approved_time %}
          {{req.approved_time|date:"Y-m-d"}}
        {% else %}
          -
        {% endif %}
      </td>
      <td>
        {% for nclass, ntext in rstatus.notes %}
        <span class="{{nclass}}">{{ntext}}</span>{% if not forloop.last %}<br>{% endif %}
        {% endfor %}
      </td>
      {% endwith %}
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'process_download_statements' pk=process.pk %}" id="download_statements">{% trans "(download all signed statements in a single mailbox file)" %}</a>
{% if user.is_superuser and process.frozen_by and not process.approved_by and not process.closed %}
<br><a href="{% url 'process_rt_ticket' pk=process.pk %}">{% trans "Draft RT ticket (old interface)" %}</a>
<br><a href="{% url 'process_approve' pk=process.pk %}">{% trans "Approve process and open RT ticket" %}</a>
{% endif %}

<h3 class="mt-3">{% trans "Log" %}</h2>

{% include "process/log_widget.html"  with entries=status.log %}

{% endblock %}